# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gitu/Xenocrypt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gitu/Xenocrypt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gitu/Xenocrypt/CMakeFiles /home/gitu/Xenocrypt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gitu/Xenocrypt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Xenocrypt

# Build rule for target.
Xenocrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Xenocrypt
.PHONY : Xenocrypt

# fast build rule for target.
Xenocrypt/fast:
	$(MAKE) -f CMakeFiles/Xenocrypt.dir/build.make CMakeFiles/Xenocrypt.dir/build
.PHONY : Xenocrypt/fast

#=============================================================================
# Target rules for targets named conquest

# Build rule for target.
conquest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conquest
.PHONY : conquest

# fast build rule for target.
conquest/fast:
	$(MAKE) -f CMakeFiles/conquest.dir/build.make CMakeFiles/conquest.dir/build
.PHONY : conquest/fast

#=============================================================================
# Target rules for targets named crypt

# Build rule for target.
crypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypt
.PHONY : crypt

# fast build rule for target.
crypt/fast:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/build
.PHONY : crypt/fast

#=============================================================================
# Target rules for targets named learn

# Build rule for target.
learn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learn
.PHONY : learn

# fast build rule for target.
learn/fast:
	$(MAKE) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/build
.PHONY : learn/fast

#=============================================================================
# Target rules for targets named pseudo

# Build rule for target.
pseudo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pseudo
.PHONY : pseudo

# fast build rule for target.
pseudo/fast:
	$(MAKE) -f CMakeFiles/pseudo.dir/build.make CMakeFiles/pseudo.dir/build
.PHONY : pseudo/fast

#=============================================================================
# Target rules for targets named videocolour

# Build rule for target.
videocolour: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videocolour
.PHONY : videocolour

# fast build rule for target.
videocolour/fast:
	$(MAKE) -f CMakeFiles/videocolour.dir/build.make CMakeFiles/videocolour.dir/build
.PHONY : videocolour/fast

#=============================================================================
# Target rules for targets named xeno

# Build rule for target.
xeno: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xeno
.PHONY : xeno

# fast build rule for target.
xeno/fast:
	$(MAKE) -f CMakeFiles/xeno.dir/build.make CMakeFiles/xeno.dir/build
.PHONY : xeno/fast

src/Xenocrypt.o: src/Xenocrypt.cpp.o
.PHONY : src/Xenocrypt.o

# target to build an object file
src/Xenocrypt.cpp.o:
	$(MAKE) -f CMakeFiles/Xenocrypt.dir/build.make CMakeFiles/Xenocrypt.dir/src/Xenocrypt.cpp.o
.PHONY : src/Xenocrypt.cpp.o

src/Xenocrypt.i: src/Xenocrypt.cpp.i
.PHONY : src/Xenocrypt.i

# target to preprocess a source file
src/Xenocrypt.cpp.i:
	$(MAKE) -f CMakeFiles/Xenocrypt.dir/build.make CMakeFiles/Xenocrypt.dir/src/Xenocrypt.cpp.i
.PHONY : src/Xenocrypt.cpp.i

src/Xenocrypt.s: src/Xenocrypt.cpp.s
.PHONY : src/Xenocrypt.s

# target to generate assembly for a file
src/Xenocrypt.cpp.s:
	$(MAKE) -f CMakeFiles/Xenocrypt.dir/build.make CMakeFiles/Xenocrypt.dir/src/Xenocrypt.cpp.s
.PHONY : src/Xenocrypt.cpp.s

src/conquest.o: src/conquest.cpp.o
.PHONY : src/conquest.o

# target to build an object file
src/conquest.cpp.o:
	$(MAKE) -f CMakeFiles/conquest.dir/build.make CMakeFiles/conquest.dir/src/conquest.cpp.o
.PHONY : src/conquest.cpp.o

src/conquest.i: src/conquest.cpp.i
.PHONY : src/conquest.i

# target to preprocess a source file
src/conquest.cpp.i:
	$(MAKE) -f CMakeFiles/conquest.dir/build.make CMakeFiles/conquest.dir/src/conquest.cpp.i
.PHONY : src/conquest.cpp.i

src/conquest.s: src/conquest.cpp.s
.PHONY : src/conquest.s

# target to generate assembly for a file
src/conquest.cpp.s:
	$(MAKE) -f CMakeFiles/conquest.dir/build.make CMakeFiles/conquest.dir/src/conquest.cpp.s
.PHONY : src/conquest.cpp.s

src/crypt.o: src/crypt.cpp.o
.PHONY : src/crypt.o

# target to build an object file
src/crypt.cpp.o:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/src/crypt.cpp.o
.PHONY : src/crypt.cpp.o

src/crypt.i: src/crypt.cpp.i
.PHONY : src/crypt.i

# target to preprocess a source file
src/crypt.cpp.i:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/src/crypt.cpp.i
.PHONY : src/crypt.cpp.i

src/crypt.s: src/crypt.cpp.s
.PHONY : src/crypt.s

# target to generate assembly for a file
src/crypt.cpp.s:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/src/crypt.cpp.s
.PHONY : src/crypt.cpp.s

src/learn.o: src/learn.cpp.o
.PHONY : src/learn.o

# target to build an object file
src/learn.cpp.o:
	$(MAKE) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/src/learn.cpp.o
.PHONY : src/learn.cpp.o

src/learn.i: src/learn.cpp.i
.PHONY : src/learn.i

# target to preprocess a source file
src/learn.cpp.i:
	$(MAKE) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/src/learn.cpp.i
.PHONY : src/learn.cpp.i

src/learn.s: src/learn.cpp.s
.PHONY : src/learn.s

# target to generate assembly for a file
src/learn.cpp.s:
	$(MAKE) -f CMakeFiles/learn.dir/build.make CMakeFiles/learn.dir/src/learn.cpp.s
.PHONY : src/learn.cpp.s

src/pseudo.o: src/pseudo.cpp.o
.PHONY : src/pseudo.o

# target to build an object file
src/pseudo.cpp.o:
	$(MAKE) -f CMakeFiles/pseudo.dir/build.make CMakeFiles/pseudo.dir/src/pseudo.cpp.o
.PHONY : src/pseudo.cpp.o

src/pseudo.i: src/pseudo.cpp.i
.PHONY : src/pseudo.i

# target to preprocess a source file
src/pseudo.cpp.i:
	$(MAKE) -f CMakeFiles/pseudo.dir/build.make CMakeFiles/pseudo.dir/src/pseudo.cpp.i
.PHONY : src/pseudo.cpp.i

src/pseudo.s: src/pseudo.cpp.s
.PHONY : src/pseudo.s

# target to generate assembly for a file
src/pseudo.cpp.s:
	$(MAKE) -f CMakeFiles/pseudo.dir/build.make CMakeFiles/pseudo.dir/src/pseudo.cpp.s
.PHONY : src/pseudo.cpp.s

src/videocolour.o: src/videocolour.cpp.o
.PHONY : src/videocolour.o

# target to build an object file
src/videocolour.cpp.o:
	$(MAKE) -f CMakeFiles/videocolour.dir/build.make CMakeFiles/videocolour.dir/src/videocolour.cpp.o
.PHONY : src/videocolour.cpp.o

src/videocolour.i: src/videocolour.cpp.i
.PHONY : src/videocolour.i

# target to preprocess a source file
src/videocolour.cpp.i:
	$(MAKE) -f CMakeFiles/videocolour.dir/build.make CMakeFiles/videocolour.dir/src/videocolour.cpp.i
.PHONY : src/videocolour.cpp.i

src/videocolour.s: src/videocolour.cpp.s
.PHONY : src/videocolour.s

# target to generate assembly for a file
src/videocolour.cpp.s:
	$(MAKE) -f CMakeFiles/videocolour.dir/build.make CMakeFiles/videocolour.dir/src/videocolour.cpp.s
.PHONY : src/videocolour.cpp.s

src/xeno.o: src/xeno.cpp.o
.PHONY : src/xeno.o

# target to build an object file
src/xeno.cpp.o:
	$(MAKE) -f CMakeFiles/xeno.dir/build.make CMakeFiles/xeno.dir/src/xeno.cpp.o
.PHONY : src/xeno.cpp.o

src/xeno.i: src/xeno.cpp.i
.PHONY : src/xeno.i

# target to preprocess a source file
src/xeno.cpp.i:
	$(MAKE) -f CMakeFiles/xeno.dir/build.make CMakeFiles/xeno.dir/src/xeno.cpp.i
.PHONY : src/xeno.cpp.i

src/xeno.s: src/xeno.cpp.s
.PHONY : src/xeno.s

# target to generate assembly for a file
src/xeno.cpp.s:
	$(MAKE) -f CMakeFiles/xeno.dir/build.make CMakeFiles/xeno.dir/src/xeno.cpp.s
.PHONY : src/xeno.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Xenocrypt"
	@echo "... conquest"
	@echo "... crypt"
	@echo "... edit_cache"
	@echo "... learn"
	@echo "... pseudo"
	@echo "... rebuild_cache"
	@echo "... videocolour"
	@echo "... xeno"
	@echo "... src/Xenocrypt.o"
	@echo "... src/Xenocrypt.i"
	@echo "... src/Xenocrypt.s"
	@echo "... src/conquest.o"
	@echo "... src/conquest.i"
	@echo "... src/conquest.s"
	@echo "... src/crypt.o"
	@echo "... src/crypt.i"
	@echo "... src/crypt.s"
	@echo "... src/learn.o"
	@echo "... src/learn.i"
	@echo "... src/learn.s"
	@echo "... src/pseudo.o"
	@echo "... src/pseudo.i"
	@echo "... src/pseudo.s"
	@echo "... src/videocolour.o"
	@echo "... src/videocolour.i"
	@echo "... src/videocolour.s"
	@echo "... src/xeno.o"
	@echo "... src/xeno.i"
	@echo "... src/xeno.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

